version: 0.2
phases:
  pre_build:
    commands:
      - echo "Config GIT for private repo"
      - git config --global url."https://$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/"
      - echo Logging in to ECR.........................................................
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo $GITHUB_TOKEN
      - echo "Building binary..."
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-extldflags "-static" -s -w' -o pse main.go
      - ls -lrth pse
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Running tests..."
      - go test ./...
  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push --all-tags $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
