name: Go Build (Windows)

on: [push, pull_request]

jobs:
  install:
    runs-on: windows-latest

    steps:

    - name: check verison
      run: $PSVersionTable

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup pse
      env:
        INVISIRISK_PORTAL: https://app.stage.invisirisk.com
        INVISIRISK_JWT_TOKEN: vVghHjvY_Z7wOtH9bMHI3T6RgyML0MdgG6TW-gyRTJpvivnKjMpGH-uImz8OUGHPBfk7ZiprFvCFT7UwIfpSHQ
      run: |
        Start-Process powershell -ArgumentList "-Command", "& '.\pse.exe' serve --config cfg.yaml --leaks leaks.toml --policy policy.json *> pse.log" -WindowStyle Hidden
        sleep 15
        netsh winhttp set proxy proxy-server="127.0.0.1:3128"
        Get-Process

    - name: Check if pse is running 
      run: |
        $processName = "pse"  # Without .exe extension
        $process = Get-Process -Name $processName -ErrorAction SilentlyContinue
        if ($process) {
        Write-Host "Process $processName is running (PID: $($process.Id))"
        } else {
        Write-Host "Process $processName is not running"
         }
        netsh winhttp show proxy

    - name: Configure Certificate
      env:
        HTTP_PROXY: http://127.0.0.1:3128
        HTTPS_PROXY: http://127.0.0.1:3128
      #shell: pwsh
      run: |
        netsh winhttp show proxy
        Invoke-WebRequest -Uri "https://pse.invisirisk.com/ca" -OutFile "pse.crt" -SkipCertificateCheck -Proxy "http://127.0.0.1:3128"
        ls
        cat pse.crt
        Import-Certificate -FilePath .\\pse.crt -CertStoreLocation Cert:\LocalMachine\Root

        
        
    - name: Start session
      env:
        HTTP_PROXY: http://127.0.0.1:3128
        HTTPS_PROXY: http://127.0.0.1:3128
      run: |
        curl https://google.com
        Invoke-WebRequest -Uri 'https://pse.invisirisk.com/start' -Method POST -Headers $headers -Body $params -UseBasicParsing
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      env:
        HTTP_PROXY: http://127.0.0.1:3128
        HTTPS_PROXY: http://127.0.0.1:3128
      run: npm install
    
    - name: End Session
      env:
        HTTP_PROXY: http://127.0.0.1:3128
        HTTPS_PROXY: http://127.0.0.1:3128
      run: Invoke-WebRequest -Uri 'https://pse.invisirisk.com/end' -Method POST -Headers $headers -Body $params -UseBasicParsing -Proxy "http://127.0.0.1:3128"
