name: Go Build (Windows)

on: [push, pull_request]

jobs:
  create_scan_in_IR_Portal:
    runs-on: ubuntu-latest
    outputs:
      scan_id: ${{ steps.parseResponse.outputs.scan_id }}
    steps:
      - name: Initiating SBOM Scan
        id: createScan
        uses: fjogeleit/http-request-action@v1.15.1
        with:
          url: 'https://app.stage.invisirisk.com/utilityapi/v1/scan'
          method: 'POST'
          data: '{"api_key": "vVghHjvY_Z7wOtH9bMHI3T6RgyML0MdgG6TW-gyRTJpvivnKjMpGH-uImz8OUGHPBfk7ZiprFvCFT7UwIfpSHQ"}'
      - name: Parse Response
        id: parseResponse
        run: echo "scan_id=${{fromJSON(steps.createScan.outputs.response).data.scan_id}}" >> "$GITHUB_OUTPUT"

  install:
    runs-on: windows-latest
    needs: [create_scan_in_IR_Portal]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup pse
      env:
        INVISIRISK_PORTAL: https://app.stage.invisirisk.com
        INVISIRISK_JWT_TOKEN: vVghHjvY_Z7wOtH9bMHI3T6RgyML0MdgG6TW-gyRTJpvivnKjMpGH-uImz8OUGHPBfk7ZiprFvCFT7UwIfpSHQ
        SCAN_ID: ${{ needs.create_scan_in_IR_Portal.outputs.scan_id }}
      run: |
        Start-Process powershell -ArgumentList "-Command", "& '.\pse.exe' serve --config cfg.yaml --leaks leaks.toml --policy policy.json *> pse.log" -WindowStyle Hidden
        ls
        sleep 15
        netsh winhttp set proxy proxy-server="127.0.0.1:3128"
        Get-Process

    - name: Check if pse is running 
      run: |
        $processName = "pse"  # Without .exe extension
        $process = Get-Process -Name $processName -ErrorAction SilentlyContinue
        if ($process) {
        Write-Host "Process $processName is running (PID: $($process.Id))"
        } else {
        Write-Host "Process $processName is not running"
         }
        netsh winhttp show proxy
        netstat -ano | findstr LISTENING


    - name: Configure Certificate
      env:
        HTTP_PROXY: http://127.0.0.1:3128
        HTTPS_PROXY: http://127.0.0.1:3128
      #shell: pwsh
      run: |
        netsh winhttp show proxy
        Invoke-WebRequest -Uri "https://pse.invisirisk.com/ca" -OutFile "pse.crt" -SkipCertificateCheck -Proxy "http://127.0.0.1:3128"
        ls
        cat pse.crt
        #Import-Certificate -FilePath .\\pse.crt -CertStoreLocation Cert:\LocalMachine\Root
        certutil -addstore -f "Root" .\\pse.crt
    

    - name: Verify certificate installation
      run: |
          Get-ChildItem -Path Cert:\LocalMachine\Root | Where-Object { $_.Subject -like "*pse*" }
      shell: pwsh    
    # - name: Start session
    #   env:
    #     HTTP_PROXY: http://127.0.0.1:3128
    #     HTTPS_PROXY: http://127.0.0.1:3128
    #     SCAN_ID: ${{ needs.create_scan_in_IR_Portal.outputs.scan_id }}
    #   run: |
    #     ls
    #     Invoke-WebRequest -Uri 'https://pse.invisirisk.com/start' -Method POST -Headers $headers -Body $params -UseBasicParsing -Verbose
    
    - name: Start session
      env:
        HTTP_PROXY: http://127.0.0.1:3128
        HTTPS_PROXY: http://127.0.0.1:3128
        SCAN_ID: ${{ needs.create_scan_in_IR_Portal.outputs.scan_id }}
      shell: pwsh
      run: |
        # Initialize retry variables
        $RETRY_DELAY = 5
        $ATTEMPT = 1
        $MAX_ATTEMPTS = 3

        # URL encode function
        function UrlEncode($value) {
            [System.Web.HttpUtility]::UrlEncode($value)
        }

        # Get Git information with fallbacks for CI environment
        try { $git_url = git config --get remote.origin.url } catch { $git_url = "https://github.com/$env:GITHUB_REPOSITORY.git" }
        try { $git_branch = git rev-parse --abbrev-ref HEAD } catch { $git_branch = $env:GITHUB_REF -replace '^refs/heads/', '' }
        try { $git_commit = git rev-parse HEAD } catch { $git_commit = $env:GITHUB_SHA }
        try { $repo_name = [System.IO.Path]::GetFileNameWithoutExtension($git_url) } catch { $repo_name = $env:GITHUB_REPOSITORY }

        # Build URL for the GitHub run
        $build_url = "$env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY/actions/runs/$env:GITHUB_RUN_ID"

        # Build parameters
        $params = @{
            builder = UrlEncode "samplegithub"
            id = UrlEncode $env:SCAN_ID
            build_id = UrlEncode $env:GITHUB_RUN_ID
            build_url = UrlEncode $build_url
            project = UrlEncode $repo_name
            workflow = UrlEncode $env:GITHUB_WORKFLOW
            builder_url = UrlEncode $env:GITHUB_SERVER_URL
            scm = UrlEncode "git"
            scm_commit = UrlEncode $git_commit
            scm_branch = UrlEncode $git_branch
            scm_origin = UrlEncode $git_url
        }

        # Convert to URL-encoded form data
        $formData = ($params.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join '&'

        Write-Host "Sending start signal to PSE service"

        # Try to send the start signal with retries
        while ($ATTEMPT -le $MAX_ATTEMPTS) {
            Write-Host "Attempt $ATTEMPT of $MAX_ATTEMPTS..."

            try {
                $response = Invoke-WebRequest -Uri 'https://pse.invisirisk.com/start' `
                    -Method POST `
                    -Headers @{
                        'Content-Type' = 'application/x-www-form-urlencoded'
                        'User-Agent' = 'pse-action'
                    } `
                    -Body $formData `
                    -UseBasicParsing `
                    -TimeoutSec 10 `
                    -ErrorAction Stop

                Write-Host "Start signal sent successfully (HTTP $($response.StatusCode))"
                Write-Host "Response: $($response.Content)"
                exit 0
            }
            catch {
                $statusCode = $_.Exception.Response.StatusCode.value__
                $responseBody = $_.ErrorDetails.Message

                Write-Host "Failed to send start signal (HTTP $statusCode)"
                Write-Host "Response: $responseBody"

                if ($ATTEMPT -lt $MAX_ATTEMPTS) {
                    Write-Host "Retrying in $RETRY_DELAY seconds..."
                    Start-Sleep -Seconds $RETRY_DELAY
                    $RETRY_DELAY = $RETRY_DELAY * 2
                }
                $ATTEMPT++
            }
        }

        Write-Host "ERROR: Failed to send start signal after $MAX_ATTEMPTS attempts"
        exit 1

    - name: Set up Node.js
      uses: actions/setup-node@v4
      env:
        HTTP_PROXY: http://127.0.0.1:3128
        HTTPS_PROXY: http://127.0.0.1:3128
      with:
        node-version: '20'
    
    - name: Set up Docker
      #env:
        #HTTP_PROXY: http://127.0.0.1:3128
        #HTTPS_PROXY: http://127.0.0.1:3128
        #SCAN_ID: ${{ needs.create_scan_in_IR_Portal.outputs.scan_id }}
        # DOCKER_HTTP_PROXY : "http://127.0.0.1:3128"
        # DOCKER_HTTPS_PROXY : "http://127.0.0.1:3128"
        # DOCKER_NO_PROXY : "localhost,127.0.0.1"
      run: |
        #netsh winhttp set proxy proxy-server="127.0.0.1:3128"
        #netsh winhttp show proxy
        # function Discover-PSEProxyIP {
        # Write-Output "Attempting to discover PSE proxy container IP"
        # $discoveredIP = ""

        # # First, check if Docker is available
        # if (Get-Command docker -ErrorAction SilentlyContinue) {
        #     Write-Output "Docker is available, attempting to find PSE proxy container"

        #     # Try to find the container by image name
        #     Write-Output "Looking for PSE proxy container by image..."
        #     try {
        #         $pseContainers = docker ps --filter "ancestor=invisirisk/pse-proxy" --format "{{.Names}}" 2>$null | Out-String
        #         $pseContainers = $pseContainers.Trim()
        #     }
        #     catch {
        #         $pseContainers = ""
        #     }
          
        #     # If not found, try with ECR path
        #     if ([string]::IsNullOrEmpty($pseContainers)) {
        #         Write-Output "Trying with ECR path..."
        #         try {
        #             $pseContainers = docker ps --filter "ancestor=282904853176.dkr.ecr.us-west-2.amazonaws.com/invisirisk/pse-proxy" --format "{{.Names}}" 2>$null | Out-String
        #             $pseContainers = $pseContainers.Trim()
        #         }
        #         catch {
        #             $pseContainers = ""
        #         }
        #     }
          
        #     # If still not found, try with any available registry ID and region
        #     if ([string]::IsNullOrEmpty($pseContainers) -and (-not [string]::IsNullOrEmpty($env:ECR_REGISTRY_ID)) -and (-not [string]::IsNullOrEmpty($env:ECR_REGION))) {
        #         Write-Output "Trying with provided ECR registry ID and region..."
        #         try {
        #             $pseContainers = docker ps --filter "ancestor=$($env:ECR_REGISTRY_ID).dkr.ecr.$($env:ECR_REGION).amazonaws.com/invisirisk/pse-proxy" --format "{{.Names}}" 2>$null | Out-String
        #             $pseContainers = $pseContainers.Trim()
        #         }
        #         catch {
        #             $pseContainers = ""
        #         }
        #     }
          
        #     # If containers found, get the IP of the first one
        #     if (-not [string]::IsNullOrEmpty($pseContainers)) {
        #         $containerName = ($pseContainers -split "`n")[0].Trim()
        #         Write-Output "Found PSE proxy container: $containerName"
        #         try {
        #             $discoveredIP = docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $containerName 2>$null | Out-String
        #             $discoveredIP = $discoveredIP.Trim()
        #             Write-Output "Discovered PSE proxy IP: $discoveredIP"
        #         }
        #         catch {
        #             $discoveredIP = ""
        #         }
        #     }
        #     else {
        #         Write-Output "No PSE proxy containers found by image name"
        #     }
        # }
        # else {
        #     Write-Output "Docker is not available, cannot discover container directly"
        # }
      
        # # Try hostname resolution methods if Docker discovery failed
        # if ([string]::IsNullOrEmpty($discoveredIP)) {
        #     # Basic hostname resolution - replace with your actual implementation
        #     try {
        #         if (-not [string]::IsNullOrEmpty($env:PROXY_HOSTNAME)) {
        #             $discoveredIP = [System.Net.Dns]::GetHostAddresses($env:PROXY_HOSTNAME)[0].IPAddressToString
        #             Write-Output "Resolved hostname $($env:PROXY_HOSTNAME) to IP: $discoveredIP"
        #         }
        #     }
        #     catch {
        #         Write-Output "Failed to resolve hostname: $($_.Exception.Message)"
        #         $discoveredIP = ""
        #     }
        # }
      
        # return $discoveredIP
        # }
          
        # # If PROXY_IP is not set, try to discover it
        # if ([string]::IsNullOrEmpty($env:PROXY_IP)) {
        #     if ([string]::IsNullOrEmpty($env:PROXY_HOSTNAME)) {
        #         Write-Output "PROXY_IP or PROXY_HOSTNAME not provided, attempting to discover PSE proxy IP"
        #     }
        #     else {
        #         Write-Output "PROXY_HOSTNAME provided but PROXY_IP not set, resolving hostname to IP"
        #     }
          
        #     $discoveredIP = Discover-PSEProxyIP
          
        #     if (-not [string]::IsNullOrEmpty($discoveredIP)) {
        #         Write-Output "Successfully discovered PSE proxy IP: $discoveredIP"
                
        #         # Set environment variables in current PowerShell session
        #         $env:PROXY_IP = $discoveredIP
        #         $env:Discover_PSEProxyIP = $discoveredIP
                
        #         # Set GitHub Actions output
        #         if (-not [string]::IsNullOrEmpty($env:GITHUB_OUTPUT)) {
        #             Add-Content -Path $env:GITHUB_OUTPUT -Value "PSE_PROXY_IP=$discoveredIP"
        #             Add-Content -Path $env:GITHUB_OUTPUT -Value "Discover_PSEProxyIP=$discoveredIP"
        #         }
                
        #         # Set GitHub Environment variables for subsequent steps
        #         if (-not [string]::IsNullOrEmpty($env:GITHUB_ENV)) {
        #             Add-Content -Path $env:GITHUB_ENV -Value "PSE_PROXY_IP=$discoveredIP"
        #             Add-Content -Path $env:GITHUB_ENV -Value "Discover_PSEProxyIP=$discoveredIP"
        #         }
                
        #         Write-Output "Environment variables set: PROXY_IP and Discover_PSEProxyIP"
        #         Write-Output "PROXY_IP: $env:PROXY_IP"
        #         Write-Output "Discover_PSEProxyIP: $env:Discover_PSEProxyIP"
        #     }
        #     else {
        #         Write-Error "ERROR: Could not discover PSE proxy IP automatically"
        #         Write-Output "This may happen if the PSE proxy container is not running or not accessible"
        #         Write-Output "You can provide proxy_ip or proxy_hostname input parameter to resolve this issue"
        #         exit 1
        #     }
        # }
        #$dockerCertsDir = "$env:USERPROFILE\.docker\certs.d"
        #New-Item -ItemType Directory -Path $dockerCertsDir -Force
        #Copy-Item -Path "pse.crt" -Destination "$dockerCertsDir\ca.crt" -Force
        docker pull ubuntu
        docker build --no-cache --build-arg ir_proxy=http://${PROXY_IP}:3128 --build-arg host_ip=$PROXY_IP --build-arg SCAN_ID=$SCAN_ID -t ir:latest .
        
        
    - name: Install dependencies
      env:
        HTTP_PROXY: http://127.0.0.1:3128
        HTTPS_PROXY: http://127.0.0.1:3128
      run: |
        $env:NODE_EXTRA_CA_CERTS = "$(Get-Location)\pse.crt"
        $env:NODE_EXTRA_CA_CERTS
        npm install
    
    - name: End Session
      env:
        HTTP_PROXY: http://127.0.0.1:3128
        HTTPS_PROXY: http://127.0.0.1:3128
        SCAN_ID: ${{ needs.create_scan_in_IR_Portal.outputs.scan_id }}
      run: Invoke-WebRequest -Uri 'https://pse.invisirisk.com/end' -Method POST -Headers $headers -Body $params -UseBasicParsing -Proxy "http://127.0.0.1:3128"

    - name: List logs maybe
      run: cat pse.log
